"""changes for demo

Revision ID: 43c24fc4dd24
Revises: 386d5c61a29b
Create Date: 2019-05-30 13:20:54.504462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43c24fc4dd24'
down_revision = '386d5c61a29b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('is_demo', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_introduced', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_introduced')
    op.drop_column('dataset', 'is_demo')
    # ### end Alembic commands ###
