"""mark task assigned by admin

Revision ID: ab06eac38963
Revises: 70fb9f3860b1
Create Date: 2019-09-16 12:23:43.694821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab06eac38963'
down_revision = '70fb9f3860b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('admin_assigned', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'admin_assigned')
    # ### end Alembic commands ###
