"""add email confirmation field

Revision ID: e58a3596b899
Revises: 878e8193ae4d
Create Date: 2019-03-26 15:05:01.522435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e58a3596b899'
down_revision = '878e8193ae4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_confirmed')
    # ### end Alembic commands ###
